properties:
  tillage:occurred:
    type: boolean
    required: true
  tillage:type:
    type: enum
    enum:
     - conventional
     - conservation
     - unknown
  tillage:events:
    type: int32
    minimum: 0
  tillage:depth:
    type: double
    minimum: 0
  tillage:spacing:
    type: double
    exclusiveMinimum: 0
  tillage:angle:
    type: int32
    minimum: 0
    maximum: 90
